apiVersion: apps/v1

kind: Deployment

metadata:
  name: spring-boot-load-balancer-k8s-deployment

  labels:
    app: spring-boot-load-balancer-k8s

spec:
  replicas: 3

  selector:
    matchLabels:
      app: spring-boot-load-balancer-k8s

  template:
    metadata:
      labels:
        app: spring-boot-load-balancer-k8s

    spec:
      containers:
        - name: spring-boot-load-balancer-k8s

          image: iamgovindthakur/spring-boot-load-balancer-k8s:latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: spring-boot-load-balancer-k8s-service
spec:
  type: NodePort
  selector:
    app: spring-boot-load-balancer-k8s
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30100
